# Generated by Django 5.2.3 on 2025-06-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_clienteprofile_prestadorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
