# Generated by Django 5.2.3 on 2025-06-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_service'),
        ('cervice', '0003_remove_service_prestador_servicerequest_proposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
