# Generated by Django 5.2.3 on 2025-06-30 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('cervice', '0003_remove_service_prestador_servicerequest_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cervice.servicerequest'),
        ),
    ]
